name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    environment: Build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Build and Test
      id: build
      shell: powershell
      run: |
          .\build.ps1 -Task Test -Bootstrap -ErrorAction Stop
          "ModulePath=$($env:BHBuildOutput)" | Add-Content "$($env:GITHUB_OUTPUT)"

    - name: Publish Windows Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      with:
        files: |
          tests/out/*.xml

    - uses: actions/upload-artifact@v4
      with:
        name: MilestoneSystems.PowerShell.MediaDB
        path: ${{ steps.build.outputs.ModulePath }}
