name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    environment: Build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Test
      id: test
      shell: powershell
      run: |
          .\build.ps1 -Task Test -Bootstrap -ErrorAction Stop
          "BHBuildOutput=$($env:BHBuildOutput)" | Add-Content "$($env:GITHUB_OUTPUT)"

