name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    environment: Build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test
      shell: powershell
      run: ./build.ps1 -Task Test -Bootstrap

