name: Testing
on:
  workflow_dispatch:
jobs:
  test:
    name: Testing
    runs-on: windows-latest
    environment: Build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test
      id: test
      shell: powershell
      run: |
          Get-PackageProvider -Name Nuget -ForceBootstrap | Out-Null
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          if ((Test-Path -Path ./requirements.psd1)) {
              if (-not (Get-Module -Name PSDepend -ListAvailable)) {
                  Install-Module -Name PSDepend -Repository PSGallery -Scope CurrentUser -Force
              }
              Import-Module -Name PSDepend -Verbose:$false
              Invoke-PSDepend -Path './requirements.psd1' -Install -Import -Force -WarningAction SilentlyContinue
          } else {
              Write-Warning 'No [requirements.psd1] found. Skipping build dependency installation.'
          }
          Get-Command Update-Metadata -All

